dual_motion_robot:
  #Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

 
  # Position Controllers ---------------------------------------

  wheel_L_joint_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_L_joint
    pid: {p: 2.0, i: 1, d: 0.5}
      
      
  wheel_R_joint_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: wheel_R_joint
    pid: {p: 2.0, i: 1, d: 0.5}
    
    
  gazebo_ros_control:
    pid_gains:
      wheel_L_joint: {p: 10.0, i: 1.0, d: 0.5}
      wheel_R_joint: {p: 10.0, i: 1.0, d: 0.5}
      # joint_3: {p: 100.0, i: 1.0, d: 1.0}
      # joint_4: {p: 100.0, i: 1.0, d: 1.0}
